name: Build and Upload JAR

on:
  push:
    branches:
      - develop
      - feature/upload-jar

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean install

      - name: Upload JAR to Azure Blob
        run: |
          az storage blob upload \
            --account-name ${{ secrets.AZURE_STORAGE_ACCOUNT }} \
            --container-name ${{ secrets.AZURE_STORAGE_CONTAINER }} \
            --name sampleapp.jar \
            --file target/sampleapp-1.0-SNAPSHOT.jar \
            --sas-token "${{ secrets.AZURE_STORAGE_SAS_TOKEN }}"
