    az storage blob upload \
            --account-name $AZURE_STORAGE_ACCOUNT \
            --container-name $AZURE_STORAGE_CONTAINER \
            --name sampleapp.jar \
            --file target/sampleapp-1.0-SNAPSHOT.jar \
            --sas-token "$AZURE_STORAGE_SAS_TOKEN"
            --overwrite  
